### PR TITLE
Add Fedora CoreOS

### PR DESCRIPTION
**Pull request by rugk**
By creating an Ignition file with YAML this can be an easy first step for provisioning machines in an automatic way of course (no input needed at installation time).

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Perhaps this belongs in hypervisors or network emulators (if that is the intent here), but not sure this fits here

**Comment by rugk** [comment]
It's certainly not an emulator and a hypervisor hmm… also is not. You could even deploy it on bare metal, but it is IMHO mainly thought for cloud deployment that is correct.

**Comment by itdependsnetworks** [comment]
Sorry, I am failing to see how this fits in with the network automation. Can you provide a use case?

**Comment by rugk** [comment]
Well… an automatic installation, upgrades etc. You use a YAML file to define your machine (similar to Ansible, but it does not need an external SSH connection and does not execute shell commands) and it is automatically provisioned. See e.g. https://www.youtube.com/watch?v=JepNm7R0LSo for details.
You can of course use Ansible on top of that, so you have a machine running in no time and Ansible can then kick in.

**Comment by itdependsnetworks** [comment]
The interest in Ansible (and similar) is in relation to its network integrations, how does this compare from that network automation first perspective? The use case mentioned does not seem to.

**Comment by rugk** [comment]
Ahh, that was not clear for me in the Ansible sections. Well of course you can configure things like [NIC](https://docs.fedoraproject.org/en-US/fedora-coreos/customize-nic/), [hostname](https://docs.fedoraproject.org/en-US/fedora-coreos/hostname/) or a simple static IP [here too](https://docs.fedoraproject.org/en-US/fedora-coreos/static-ip-config/).

**Comment by itdependsnetworks** [comment]
Yes, but not within core competency of the attention of this repo.

**Pull request closed without merging**
